//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazonInterview {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AmazonInterview.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 82 180 55 168 41 179 59 139 71 6 12 135 139 73 157 4 74 195 60 45 28 67 136 58 55 22 60 33 84 48 185 118 29 41 86 22 172 145 114 43 103 126 130 43 152 87 199 26 34 59 24 63 79 160 73 86 134 133 71 18 182 57 89 163 98 175 137 70 73 3 113 176 130 43 19 34 83 170 12 117 30 36 132 61 197 5 99 131 91 171 102 25 28 143 188 126 118 77 148 143 81 61 120 163 56 91 149 91 62 161 161 44 198 93 57 195 51 156 78 142 127 132 119 107 75 59 33 146 136 133 89 169 146 161 84 3 5 33 46 67 195 7 63 193 53 120 140 56 28 170 1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string expenditures {
            get {
                return ResourceManager.GetString("expenditures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 115 176 24 198 161 151 59 37 83 7 190 64 37 3 93 130 176 28 20 154 126 111 33 96 45 110 93 99 157 187 85 72 116 61 70 77 12 81 66 47 40 56 64 78 11 109 8 188 137 180 94 64 91 127 160 137 190 5 188 147 145 25 171 61 86 193 90 50 75 108 98 115 164 114 145 176 23 106 116 112 86 10 176 130 89 89 67 31 46 7 178 191 32 101 4 118 95 94 168 122 2 18 37 119 132 135 47 107 41 163 20 79 173 148 9 62 189 28 94 36 35 24 27 67 78 184 137 173 78 106 95 33 76 84 104 9 19 151 68 12 114 88 92 39 189 53 53 178 82 147 14 69 12 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string expenditures2 {
            get {
                return ResourceManager.GetString("expenditures2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 402159386 855281517 951
        ///78784642 628778006 814819524
        ///257121863 512690385 568531630
        ///191483712 133998276 219876078
        ///24946722 394491791 807847150
        ///143326758 516353864 567487888
        ///304114857 559108942 565423924
        ///24228588 833146215 849130550
        ///357531390 806210643 816693281
        ///334477 156186458 287472520
        ///265206289 261342096 636632143
        ///225381174 6069913 377107860
        ///9905238 250163927 572148214
        ///262788819 343477965 418368162
        ///20042752 250950342 848414359
        ///157351215 199949059 526416674
        ///38915168 674461015 789937002
        ///857 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string gridland1 {
            get {
                return ResourceManager.GetString("gridland1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 9 3
        ///2 1 5
        ///2 2 4
        ///2 8 8.
        /// </summary>
        internal static string gridland2 {
            get {
                return ResourceManager.GetString("gridland2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1
        ///2
        ///1
        ///1
        ///1
        ///2
        ///1
        ///1
        ///2
        ///2
        ///2
        ///2
        ///1
        ///2
        ///3
        ///2
        ///2
        ///1
        ///1
        ///2
        ///2
        ///1
        ///3
        ///3
        ///4
        ///4
        ///3
        ///4
        ///4
        ///2
        ///3
        ///2
        ///2
        ///2
        ///4
        ///1
        ///2
        ///4
        ///1
        ///2
        ///2
        ///1
        ///1
        ///1
        ///3
        ///1
        ///4
        ///4
        ///4
        ///2
        ///4
        ///3
        ///4
        ///4
        ///1
        ///4
        ///2
        ///4
        ///3
        ///1
        ///3
        ///1
        ///2
        ///4
        ///4
        ///4
        ///3
        ///2
        ///2
        ///1
        ///1
        ///4
        ///1
        ///3
        ///2
        ///3
        ///1
        ///3
        ///2
        ///1
        ///1
        ///1
        ///2
        ///3
        ///2
        ///2
        ///1
        ///3
        ///3
        ///3
        ///4
        ///3
        ///2
        ///2
        ///3
        ///4
        ///1
        ///1
        ///1
        ///2
        ///2
        ///3
        ///1
        ///4
        ///4
        ///1
        ///4
        ///3
        ///1
        ///2
        ///2
        ///3
        ///1
        ///1
        ///2
        ///2
        ///1
        ///3
        ///3
        ///1
        ///4
        ///4
        ///2
        ///4
        ///3
        ///4
        ///4
        ///4
        ///1
        ///3
        ///3
        ///3
        ///2
        ///2
        ///3
        ///3
        ///2
        ///1
        ///1
        ///3
        ///2
        ///1
        ///1
        ///1
        ///2
        ///3
        ///4
        ///3
        ///2
        ///1
        ///2
        ///2
        ///4
        ///1
        ///1
        ///2
        ///2
        ///3
        ///3
        ///1
        ///1
        ///2
        ///3
        ///3
        ///2
        ///3
        ///2
        ///3
        ///4
        ///2
        ///2        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string maximumpalindromes_ans {
            get {
                return ResourceManager.GetString("maximumpalindromes_ans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2
        ///1
        ///1
        ///2
        ///2
        ///2
        ///1
        ///3
        ///2
        ///3
        ///3
        ///2
        ///1
        ///3
        ///1
        ///1
        ///4
        ///1
        ///2
        ///1
        ///1
        ///1
        ///3
        ///1
        ///1
        ///1
        ///1
        ///2
        ///1
        ///3
        ///4
        ///2
        ///1
        ///2
        ///1
        ///4
        ///2
        ///1
        ///1
        ///1
        ///4
        ///2
        ///2
        ///2
        ///2
        ///1
        ///1
        ///1
        ///3
        ///4
        ///2
        ///1
        ///4
        ///2
        ///2
        ///4
        ///4
        ///1
        ///2
        ///3
        ///1
        ///4
        ///1
        ///1
        ///3
        ///2
        ///1
        ///1
        ///2
        ///1
        ///1
        ///2
        ///1
        ///1
        ///4
        ///2
        ///1
        ///2
        ///3
        ///3
        ///2
        ///1
        ///1
        ///3
        ///1
        ///3
        ///4
        ///4
        ///1
        ///2
        ///4
        ///4
        ///1
        ///2
        ///1
        ///2
        ///3
        ///3
        ///1
        ///1
        ///1
        ///1
        ///1
        ///1
        ///1
        ///2
        ///2
        ///3
        ///1
        ///4
        ///1
        ///1
        ///3
        ///1
        ///1
        ///1
        ///3
        ///1
        ///1
        ///2
        ///1
        ///1
        ///2
        ///1
        ///3
        ///2
        ///3
        ///1
        ///3
        ///1
        ///3
        ///2
        ///2
        ///1
        ///2
        ///3
        ///1
        ///1
        ///1
        ///2
        ///2
        ///1
        ///1
        ///3
        ///2
        ///1
        ///1
        ///1
        ///2
        ///1
        ///3
        ///3
        ///3
        ///1
        ///3
        ///1
        ///1
        ///2
        ///2
        ///1
        ///1
        ///2
        ///1
        ///2
        ///2
        ///3
        ///3
        ///1
        ///1
        ///1
        ///3        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string maximumpalindromes_ans2 {
            get {
                return ResourceManager.GetString("maximumpalindromes_ans2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8
        ///3
        ///60480
        ///144
        ///16
        ///7
        ///544320
        ///14
        ///55440
        ///840
        ///3
        ///144
        ///2
        ///7
        ///2
        ///5040
        ///1995840
        ///12
        ///2
        ///181440
        ///144
        ///18
        ///2520
        ///3
        ///1
        ///84
        ///240
        ///1
        ///7
        ///2
        ///36
        ///7
        ///1
        ///17640
        ///1440
        ///2520
        ///1814400
        ///168
        ///48
        ///443520
        ///54
        ///16329600
        ///2520
        ///1320
        ///99792000
        ///6
        ///4320
        ///48
        ///1200
        ///141120
        ///9
        ///740299127
        ///556755193
        ///1
        ///12
        ///14
        ///60480
        ///12
        ///240
        ///1
        ///20160
        ///3
        ///8
        ///1200
        ///12
        ///4
        ///17640
        ///48
        ///16
        ///3
        ///7
        ///720
        ///3
        ///2
        ///840
        ///360
        ///544320
        ///17640
        ///17640
        ///3
        ///4
        ///1270080
        ///72
        ///240
        ///89812800
        ///8
        ///7
        ///360
        ///16
        ///20
        ///54
        ///6
        ///48
        ///99792000
        ///720
        ///5
        ///240
        ///192
        ///2
        ///5040
        ///2
        ///119750400        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string maximumpalindromes_ans3 {
            get {
                return ResourceManager.GetString("maximumpalindromes_ans3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21 21
        ///4 5
        ///13 13
        ///26 26
        ///25 25
        ///1 2
        ///16 16
        ///3 3
        ///11 12
        ///12 13
        ///3 4
        ///2 3
        ///20 20
        ///8 9
        ///2 4
        ///23 24
        ///15 16
        ///25 25
        ///15 15
        ///25 26
        ///25 26
        ///15 15
        ///18 20
        ///17 19
        ///4 7
        ///10 13
        ///21 23
        ///4 7
        ///6 9
        ///6 7
        ///8 10
        ///2 3
        ///2 3
        ///11 12
        ///13 16
        ///25 25
        ///20 21
        ///2 5
        ///20 20
        ///24 25
        ///6 7
        ///26 26
        ///5 5
        ///17 17
        ///19 21
        ///17 17
        ///3 6
        ///10 13
        ///16 19
        ///15 16
        ///15 18
        ///13 15
        ///3 6
        ///1 4
        ///13 13
        ///9 12
        ///20 21
        ///23 26
        ///24 26
        ///17 17
        ///13 15
        ///16 16
        ///19 20
        ///17 20
        ///14 17
        ///1 4
        ///23 25
        ///1 2
        ///6 7
        ///11 11
        ///25 25
        ///11 14
        ///16 16
        ///18 20
        ///3 4
        ///24 26
        ///20 20
        ///21 23
        ///11 12
        ///11 11
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string maximumpalindromes_test {
            get {
                return ResourceManager.GetString("maximumpalindromes_test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13 14
        ///27 29
        ///4 4
        ///70 71
        ///36 39
        ///65 66
        ///38 38
        ///59 61
        ///49 52
        ///51 53
        ///65 67
        ///53 56
        ///15 15
        ///14 16
        ///49 49
        ///71 71
        ///12 15
        ///35 35
        ///17 18
        ///26 28
        ///61 61
        ///52 54
        ///18 20
        ///4 4
        ///64 64
        ///14 14
        ///11 11
        ///2 5
        ///55 55
        ///18 20
        ///37 40
        ///21 24
        ///73 73
        ///72 73
        ///45 47
        ///79 82
        ///57 58
        ///23 25
        ///31 31
        ///28 30
        ///63 66
        ///72 73
        ///80 83
        ///8 9
        ///13 14
        ///41 42
        ///49 51
        ///40 40
        ///9 11
        ///74 77
        ///31 34
        ///54 54
        ///75 78
        ///63 64
        ///21 22
        ///12 15
        ///13 16
        ///67 67
        ///80 83
        ///13 15
        ///82 82
        ///19 22
        ///14 14
        ///44 46
        ///69 71
        ///52 53
        ///3 3
        ///31 33
        ///1 4
        ///24 24
        ///21 21
        ///44 47
        ///31 33
        ///58 58
        ///20 23
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string maximumpalindromes_test2 {
            get {
                return ResourceManager.GetString("maximumpalindromes_test2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 31 38
        ///29 33
        ///13 34
        ///4 17
        ///15 26
        ///2 10
        ///10 33
        ///15 25
        ///18 42
        ///23 39
        ///17 21
        ///28 41
        ///29 30
        ///1 9
        ///30 34
        ///17 35
        ///2 30
        ///11 18
        ///27 28
        ///8 32
        ///18 31
        ///26 34
        ///5 23
        ///13 19
        ///39 39
        ///13 27
        ///26 43
        ///23 25
        ///32 40
        ///14 15
        ///27 38
        ///7 15
        ///18 19
        ///5 25
        ///10 25
        ///8 26
        ///4 31
        ///28 42
        ///26 39
        ///15 41
        ///2 16
        ///1 29
        ///4 22
        ///20 40
        ///5 36
        ///22 28
        ///18 35
        ///12 23
        ///24 43
        ///9 31
        ///12 20
        ///3 41
        ///6 42
        ///42 42
        ///4 13
        ///4 14
        ///15 40
        ///31 40
        ///9 22
        ///10 10
        ///1 22
        ///11 15
        ///30 37
        ///21 40
        ///16 25
        ///29 32
        ///12 32
        ///11 22
        ///16 27
        ///25 29
        ///37 43
        ///23 38
        ///20 22
        ///41 42
        ///21 37
        ///13 28
        ///13 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string maximumpalindromes_test3 {
            get {
                return ResourceManager.GetString("maximumpalindromes_test3", resourceCulture);
            }
        }
    }
}
